### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by KnifeFed** [ndonfris/vscode-fish-lsp#10]
After updating to 0.1.14:

```
node:internal/modules/cjs/loader:1375
  throw err;
  ^

Error: Cannot find module 'chalk'
Require stack:
- /Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/node_modules/fish-lsp/dist/fish-lsp
- /Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/out/server-module.js
    at Module._resolveFilename (node:internal/modules/cjs/loader:1372:15)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1028:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1033:22)
    at Module._load (node:internal/modules/cjs/loader:1182:37)
    at c._load (node:electron/js2c/node_init:2:17993)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:242:24)
    at Module.require (node:internal/modules/cjs/loader:1452:12)
    at require (node:internal/modules/helpers:135:16)
    at Object.<anonymous> (/Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/node_modules/fish-lsp/dist/fish-lsp:559:1441) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/node_modules/fish-lsp/dist/fish-lsp',
    '/Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/out/server-module.js'
  ]
}

Node.js v22.18.0
[Error - 2:02:18 PM] Server process exited with code 1.
[Info  - 2:02:18 PM] Connection to server got closed. Server will restart.
true
```

**Comment by ndonfris** [comment]
Strange. It looks like this issue might be caused by the `.vscodeignore` file ignoring the server's node_module dependencies. 

Does `/Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/node_modules/fish-lsp/` have a `node_modules/` directory? 

Could you check, if installing the node_modules for the fish-lsp for the local version fixes this before I change anything on the server? If it doesn't could you navigate to the folder, and install the dependencies? 

```sh
cd `/Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/node_modules/fish-lsp/
npm i
# restart vscode and see if the issue persists
```

Normally, if the command (using the executable): 
```sh
/Users/<username>/.vscode-insiders/extensions/ndonfris.fish-lsp-0.1.14/node_modules/fish-lsp/dist/fish-lsp info --time-only
```
exits successfully, the server is working correctly.

**Comment by deepfriedmind** [comment]
This one works fine, thank you!

**Comment by KnifeFed** [comment]
I just tried 0.1.15-pre.0 and it seems to be working. Thanks!

**Comment by KnifeFed** [comment]
So, the extension has been broken in the marketplace for 3 weeks now. Wouldn't it be preferable to release the current 0.1.15?

**Comment by ndonfris** [comment]
Yeah, sorry! I've been terribly busy lately 🙃

I was meaning to publish the vsix for the latest VS Code release earlier this week, but had to confirm fish `4.0.8` didn't introduce anything that would break the recent server changes. Plus, I've been waiting for feedback on the nightly server releases. 

Server changes will publish probably later today. Once I'm finished reviewing those, the stable release of `fish-lsp@1.0.11` will publish also include bumping this extension to a new stable version on VS Code marketplace.  

___

The server has had lots of changes related to making there be fewer issues with VS Code integration if you're interested [#104](https://github.com/ndonfris/fish-lsp/pull/104) [#107](https://github.com/ndonfris/fish-lsp/pull/107) [#108](https://github.com/ndonfris/fish-lsp/pull/108)

Since the previous minor release of the lsp, I've re-hauled the build process to bundle and embed external dependencies that VS Code might not correctly handle (embedding all assets into a single binary), added significant test coverage, added new configuration settings, and a pretty decent amount of other fixes/features to the server. 
___

More than likely, [`pre-release v0.1.15-pre.4`](https://github.com/ndonfris/vscode-fish-lsp/releases/tag/v0.1.15-pre.4) will have very little difference from the requested stable release `v0.1.15`. 

Feel free to ping me if you notice any issues with the extension in the meantime

**Comment by KnifeFed** [comment]
Thank you for the detailed answer! v0.1.15-pre.4 works great!

**Comment by ndonfris** [comment]
Awesome! Thanks again for the feedback. 🙏 

Just published the [server](https://github.com/ndonfris/fish-lsp/releases/tag/v1.0.11) and the [VS Code extension](https://marketplace.visualstudio.com/items?itemName=ndonfris.fish-lsp) to the marketplace.
